# Working with numerical data in Python

The "data" in Data Analysis typically refers to numerical data, e.g., stock prices, sales figures, sensor measurements, sports scores, database tables, etc. The Numpy library provides specialized data structures, functions, and other tools for numerical computing in Python. 

Let's work through an example to see why & how to use Numpy for working with numerical data.

> Suppose we want to use climate data like the temperature, rainfall, and humidity to determine if a region is well suited for growing apples. A simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions like the average temperature (in degrees Fahrenheit), rainfall (in millimeters) & average relative humidity (in percentage) as a linear equation.    $ yield\_of\_apples = w1 * temperature + w2 * rainfall + w3 * humidity $

We're expressing the yield of apples as a weighted sum of the temperature, rainfall, and humidity. This equation is an approximation since the actual relationship may not necessarily be linear, and there may be other factors involved. But a simple linear model like this often works well in practice.

Based on some statical analysis of historical data, we might come up with reasonable values for the weights w1, w2, and w3. Here's an example set of values:



In [8]:
w1,w2,w3 = 0.3,0.2,0.5 # 不妨做的假设

Given some climate data for a region, we can now predict the yield of apples. Here's some sample data:

|  地区   | Temp(F)  |  Ranifall(mm)  | Humidity(%)  |
|  ----   | ----  |  ----  | ----  |
|  Kanto   | 73  |  67  | 43  |
|  Johto   | 91  |  88  | 64  |
|  Hoenn   | 87  |  134  | 58  |
|  Sinnoh   | 102  |  43  | 47  |
|  Unova   | 69  |  96  | 70  |

To begin, we can define some variables to record climate data for a region.




In [9]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

We can now substitute these variables into the linear equation to predict the yield of apples.

In [10]:
kanto_yield_apples = kanto_temp*w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

To make it slightly easier to perform the above computation for multiple regions, we can represent the climate data for each region as a vector, i.e., a list of numbers.


In [11]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

weights = [w1,w2,w3]


The three numbers in each vector represent the temperature, rainfall, and humidity data, respectively.

We can also represent the set of weights used in the formula as a vector.

In [12]:
weights

[0.3, 0.2, 0.5]

In [13]:
def crop_yield(region,weights):
    result = 0
    for x,w in zip(region,weights):
        result += x*w
    return result

In [14]:
crop_yield(kanto,weights)

56.8

# Going from Python lists to Numpy arrays

In [15]:
kanto

[73, 67, 43]

In [16]:
weights

[0.3, 0.2, 0.5]

In [17]:
import numpy as np
kanto = np.array([73,67,43])
weights = np.array([w1,w2,w3])

In [18]:
kanto * weights # 默认就是点乘

array([21.9, 13.4, 21.5])

In [19]:
np.dot(kanto,weights)

56.8

In [20]:
(kanto * weights).sum()

56.8

In [21]:
# Python lists
arr1 = range(1000000)
arr2 = range(1000000, 2000000)

# Numpy arrays
arr1_np = np.array(arr1,dtype='int64')
arr2_np = np.array(arr2,dtype='int64')

In [22]:
%%time 
result = 0
for x1,x2 in zip(arr1,arr2):
    result += x1*x2
result

Wall time: 155 ms


833332333333500000

In [23]:
%%time
np.dot(arr1_np,arr2_np)

Wall time: 1.03 ms


833332333333500000

# Multi-dimensional Numpy arrays and their benefits

In [24]:
climate_data = np.array([
    [73,67,43],
                        [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]
])

In [25]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [26]:
climate_data.shape

(5, 3)

In [27]:
climate_data.size

15

In [28]:
climate_data.dtype

dtype('int32')

In [29]:
# 1d vector
weights.shape

(3,)

In [30]:
arr2 = np.array([
    [1,2,5],
    [3,4,6],    
])

In [31]:
arr2.sum(axis=0)

array([ 4,  6, 11])

In [32]:
arr2.sum(axis=1)

array([ 8, 13])

In [33]:
arr3 = np.array([
    [[255,255,255],[0,0,0]],
    [[255,255,255],[0,0,0]],
])

In [34]:
arr3.sum(0)

array([[510, 510, 510],
       [  0,   0,   0]])

In [35]:
arr3.sum(1)

array([[255, 255, 255],
       [255, 255, 255]])

In [36]:
arr3.sum(2)

array([[765,   0],
       [765,   0]])

In [37]:
arr3.shape

(2, 2, 3)

In [38]:
arr4 = np.array([
    [[[255,1,2],[255,1,2]],[[0,0,0],[0,0,0]]],
    [[[255,1,2],[255,1,2]],[[0,0,0],[0,0,0]]],
])

In [39]:
arr4.shape

(2, 2, 2, 3)

In [40]:
arr4.sum(axis=0)

array([[[510,   2,   4],
        [510,   2,   4]],

       [[  0,   0,   0],
        [  0,   0,   0]]])

In [41]:
arr4.sum(axis=1)

array([[[255,   1,   2],
        [255,   1,   2]],

       [[255,   1,   2],
        [255,   1,   2]]])

In [42]:
arr4.sum(axis=2)

array([[[510,   2,   4],
        [  0,   0,   0]],

       [[510,   2,   4],
        [  0,   0,   0]]])

In [43]:
arr4.sum(axis=3)

array([[[258, 258],
        [  0,   0]],

       [[258, 258],
        [  0,   0]]])

In [44]:
arr3

array([[[255, 255, 255],
        [  0,   0,   0]],

       [[255, 255, 255],
        [  0,   0,   0]]])

In [45]:
arr3.shape

(2, 2, 3)

In [46]:
arr3.dtype

dtype('int32')

In [47]:
climate_data.dtype

dtype('int32')

In [48]:
arr3[0][0][0] = 333.3

In [49]:
arr3.dtype

dtype('int32')

In [50]:
arr3 = arr3.astype('float32')

In [51]:
arr3

array([[[333., 255., 255.],
        [  0.,   0.,   0.]],

       [[255., 255., 255.],
        [  0.,   0.,   0.]]], dtype=float32)

In [52]:
climate_data.shape

(5, 3)

In [53]:
weights.shape

(3,)

In [54]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [55]:
weights

array([0.3, 0.2, 0.5])

In [56]:
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

# numpy CSV 文件操作, np.genfromtxt() and np.savetxt()

In [57]:
climate_data = np.genfromtxt('climate.csv',delimiter=',',skip_header=1)

In [58]:
climate_data.shape

(10000, 3)

In [59]:
yields = climate_data @ weights

In [60]:
yields.shape

(10000,)

In [61]:
climate_results = np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [62]:
climate_results.dtype

dtype('float64')

In [63]:
np.savetxt('climate_results.csv',# txt 也可以
          climate_results,
           fmt = '%.2f',
           delimiter = ',',
           header = 'temp,rainfall,humidity,yeilds',
           comments = '',
          ) 

# Array operations,broadcasting,indexing and slicing

In [64]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [65]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [66]:
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [67]:
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [68]:
ret = arr2 /2

In [69]:
arr2.dtype

dtype('int32')

In [70]:
ret.dtype

dtype('float64')

In [71]:
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [72]:
arr2 % 3

array([[1, 2, 0, 1],
       [2, 0, 1, 2],
       [0, 1, 2, 0]], dtype=int32)

In [73]:
a = np.arange(3).reshape(3,1)

In [74]:
b = np.arange(3)

In [75]:
a * b   # 发生了 broadcasting  

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [76]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [77]:
c.shape

(3, 3)

In [78]:
a * c

array([[ 0,  0,  0],
       [ 4,  5,  6],
       [14, 16, 18]])

### Array Comparison


In [79]:
arr1 = np.array([[1,2,3],[3,4,5]])

In [80]:
arr2 = np.array([[1,2,3],[1,2,5]])

In [81]:
arr1 == arr2

array([[ True,  True,  True],
       [False, False,  True]])

In [82]:
arr1 != arr2

array([[False, False, False],
       [ True,  True, False]])

In [83]:
arr1 >= arr2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [84]:
arr1 < arr2

array([[False, False, False],
       [False, False, False]])

#### Array comparison 的一个作用是统计相同元素的个数

In [85]:
(arr1 == arr2 ).sum()   # 

4

### Array indexing and slicing

In [86]:
arr3 = np.array([
    [
        [11, 12, 13], 
     [13, 14, 19],
     [14, 15, 16]
    ], 
    
    [
        [15, 17, 21], 
     [92, 36, 18], 
    [23, 24, 29]
    ],
    
    [
        [28, 32, 3],      
     [98, 32, 23],      
     [17, 19.5, 43]
    ]
])

In [87]:
arr3.shape

(3, 3, 3)

In [88]:
# single ele
arr3[1,1,2]

18.0

In [89]:
# 第一排像素点的数值  和 最后一排像素点的数值 
arr3[[0,-1]] # 操作的是 axis 0 

array([[[11. , 12. , 13. ],
        [13. , 14. , 19. ],
        [14. , 15. , 16. ]],

       [[28. , 32. ,  3. ],
        [98. , 32. , 23. ],
        [17. , 19.5, 43. ]]])

In [90]:
# 第一排像素点 和最后一排像素点 的第一,二列  # 四个像素点
ret1 = arr3[[[0,0],[-1,-1]],[[0,1],[0,1]]] # 同时操作 axis 0 和 axis 1  
print(ret1)
print('===========')

# 或者   （推荐使用）
ret2 = arr3[[0,-1]] # 只 axis 0 第一行 和 最后一行 
ret3 = ret2[:,[0,1]] # 只 axis 1 
print(ret3)

[[[11. 12. 13.]
  [13. 14. 19.]]

 [[28. 32.  3.]
  [98. 32. 23.]]]
[[[11. 12. 13.]
  [13. 14. 19.]]

 [[28. 32.  3.]
  [98. 32. 23.]]]


In [91]:
# 第一排像素点 和最后一排像素点 的 第一二列 的R B 值
# 此时如果再用  3个 axis 一起使用就比较麻烦了

# 单独来，一个一个来 
ret1 = arr3[[0,-1]]  # axis 0 第一行 和 最后一行 
ret2 = ret1[:,[0,1]] # axis 1  第一列 和 第二列 
ret3 = ret2[:,:,[0,2]] # R 和 B 值  
print(ret3)
print('=========')

# 最后一步也可以如下：
ret4 = ret2[...,[0,2]]
print(ret4)

[[[11. 13.]
  [13. 19.]]

 [[28.  3.]
  [98. 23.]]]
[[[11. 13.]
  [13. 19.]]

 [[28.  3.]
  [98. 23.]]]


### Other way of creating Numpy arrays

In [97]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [101]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [102]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
np.random.rand(5)

array([0.21741666, 0.46677991, 0.53682894, 0.01741198, 0.33069399])

In [104]:
np.random.randn(2,3)

array([[-0.23844325, -0.44890407,  2.31376309],
       [-0.52441507, -0.3709738 ,  0.74463148]])

In [112]:
np.random.randint(2,5) # [2,5)  


2

In [113]:
np.full((2,3),32)

array([[32, 32, 32],
       [32, 32, 32]])

In [117]:
np.arange(3,10,3)

array([3, 6, 9])

In [118]:
np.linspace(3,10,3)

array([ 3. ,  6.5, 10. ])

# Exercise 练习

In [119]:
import numpy as np

In [122]:
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

In [123]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

In [126]:
print(np.__version__)
print(np.__config__)

1.19.5
<module 'numpy.__config__' from 'c:\\users\\zcb\\envs\\env01\\lib\\site-packages\\numpy\\__config__.py'>


In [128]:
v = np.zeros(10)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [135]:
mem = v.size * v.itemsize
mem

80

In [141]:
np.info(np.matmul)

matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Matrix product of two arrays.

Parameters
----------
x1, x2 : array_like
    Input arrays, scalars not allowed.
out : ndarray, optional
    A location into which the result is stored. If provided, it must have
    a shape that matches the signature `(n,k),(k,m)->(n,m)`. If not
    provided or None, a freshly-allocated array is returned.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

    .. versionadded:: 1.16
       Now handles ufunc kwargs

Returns
-------
y : ndarray
    The matrix product of the inputs.
    This is a scalar only when both x1, x2 are 1-d vectors.

Raises
------
ValueError
    If the last dimension of `a` is not the same size as
    the second-to-last dimension of `b`.

    If a scalar value is passed in.

See Also
--------
vdot : Complex-conjugating dot product.
tensordot : Sum products over arbitrary axes.
einsu

In [154]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [155]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [159]:
arr = np.arange(1,10)

In [161]:
arr = arr[::-1]

In [162]:
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [168]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [169]:
arr = [1,2,0,0,4,0]

In [170]:
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

In [172]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [179]:
np.random.rand(3,3,3)

array([[[0.95914092, 0.43745753, 0.1102739 ],
        [0.6277723 , 0.67953474, 0.68743147],
        [0.99387357, 0.99182383, 0.82668974]],

       [[0.78908196, 0.6472056 , 0.88250557],
        [0.10268903, 0.2335069 , 0.21978925],
        [0.5340684 , 0.79764071, 0.32790552]],

       [[0.96067321, 0.08845662, 0.56304683],
        [0.146159  , 0.35914403, 0.40258214],
        [0.45421523, 0.64928935, 0.94271313]]])

In [185]:
arr = np.random.randn(10,10)
print(np.max(arr))
print(np.min(arr))

2.1221069815967692
-2.3839067969544523


In [188]:
arr = np.random.randn(30)
print(np.mean(arr))

0.07927330165972281


In [207]:
arr = np.zeros((4,5))
arr[[0,-1]] = 1
arr[:,[0,-1]] = 1

In [208]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [211]:
arr = np.random.randn(3,3)

In [212]:
arr

array([[-2.88734483,  0.25539786,  1.05971115],
       [ 0.03287473, -0.10300497, -1.06449375],
       [ 0.19349006, -1.82891649, -0.75654128]])

# 100 numpy exercise 做到了16题

### 现在继续做

In [1]:
import numpy as np

In [2]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [7]:
np.info(np.pad)

 pad(*args, **kwargs)

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with

In [8]:
np.info(np.nan)

Convert a string or number to a floating point number, if possible.


In [9]:
np.nan

nan

In [12]:
np.log([-1,1,2])

<ipython-input-12-e0f2b630f1e3>:1: RuntimeWarning: invalid value encountered in log
  np.log([-1,1,2])


array([       nan, 0.        , 0.69314718])

In [13]:
0*np.nan

nan

In [18]:
if np.nan != np.nan:
    print("yes")

yes


In [19]:
np.nan in [np.nan]

True

In [20]:
help(np.nan)

Help on float object:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __int__(self, /)
 |      int(self)
 |  
 |  __le__

In [21]:
np.nan / np.nan

nan

In [23]:
np.inf > np.nan

False

In [24]:
np.inf < np.nan

False

In [25]:
np.inf == np.nan

False

In [28]:
np.nan - np.nan

nan

In [29]:
np.nan in set([np.nan])

True

In [32]:
0.3 == 3 * 0.1

False

In [36]:
0.8 * 0.3 == 0.2 * 0.12

False

In [51]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [3]:
np.nan

nan

In [4]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [6]:
np.info(np.diag)

 diag(*args, **kwargs)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> 

In [16]:
np.unravel_index(2,(6,7,8))

(0, 0, 2)

In [22]:
np.unravel_index(6,(3,5))

(1, 1)

In [23]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
np.random.randn(2,2)

array([[-0.29941096,  0.13633566],
       [ 1.14986265,  1.20281554]])

In [34]:
np.random.random((2,2))

array([[0.63576937, 0.51969098],
       [0.68002781, 0.77601447]])

In [40]:
Z = np.random.random((2,2))
print(Z)
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.87800677 0.85394929]
 [0.43509126 0.8223294 ]]
[[1.         0.94568382]
 [0.         0.87429347]]


In [41]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-41-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [42]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [43]:
np.ubyte

numpy.uint8

In [45]:
np.dtype(np.int16)

dtype('int16')

In [51]:
np.dtype('uint8')

dtype('uint8')

In [53]:
np.dtype([('f1','int16'),('f2','int32')])

dtype([('f1', '<i2'), ('f2', '<i4')])

In [55]:
color = np.dtype([("r", np.ubyte, 2),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-55-de775cdea87f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 2),


In [64]:
np.random.random((5,3)) @ np.random.random((3,2))

array([[0.88010104, 0.49133683],
       [1.37401073, 1.10796136],
       [0.84662535, 0.5128506 ],
       [0.86611916, 0.43340707],
       [0.92846741, 0.76089979]])

In [65]:
np.dot(np.random.random((5,3)), np.random.random((3,2)))

array([[0.54351698, 0.09612544],
       [0.66298915, 0.18173126],
       [0.53677539, 0.43322711],
       [0.63638154, 0.48380723],
       [0.35824231, 0.17018237]])

In [70]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

In [71]:
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])

In [93]:
arr = np.arange(10)
arr[(arr>3) & (arr<8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

In [95]:
print(sum(range(5),1))

11


In [96]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [109]:
z = np.array([1,2,3])

In [110]:
z**z

array([ 1,  4, 27], dtype=int32)

In [111]:
2 << z >> 2

array([1, 2, 4], dtype=int32)

In [112]:
z <- z

array([False, False, False])

In [113]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)

<ipython-input-113-6ecbe7defa75>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-113-6ecbe7defa75>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [114]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [117]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [121]:
np.array([1,2,3]).astype(float)

array([1., 2., 3.])

In [122]:
np.ceil(10.3)

11.0

In [124]:
np.floor(10.3)

10.0

In [131]:
np.round(10.6)

11.0

In [132]:
arr1 = np.arange(10)
arr2 = np.arange(3,12)

In [136]:
np.intersect1d(arr1,arr2)

array([3, 4, 5, 6, 7, 8, 9])

In [142]:
np.sqrt(-1)

nan

In [144]:
np.emath.sqrt(-1)

1j

In [145]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [152]:
today     = np.datetime64('today', 'D')
yes = today - np.timedelta64(1,'D')
tom = today + np.timedelta64(1,'D')

In [153]:
today,yes,tom

(numpy.datetime64('2021-01-29'),
 numpy.datetime64('2021-01-28'),
 numpy.datetime64('2021-01-30'))

In [157]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [159]:
Z = np.arange('2016-07', '2016-08',dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [160]:
np.datetime64('today')

numpy.datetime64('2021-01-29')